"""3rd migration

Revision ID: 89af369e44c4
Revises: dbab36969c08
Create Date: 2023-09-03 23:07:59.863850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89af369e44c4'
down_revision = 'dbab36969c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
