"""3rd migration

Revision ID: dbab36969c08
Revises: b34ece31871f
Create Date: 2023-09-03 23:02:22.829401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbab36969c08'
down_revision = 'b34ece31871f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
